
---
version: '3.3'
services:
ubuntu-xfce-vnc-novnc:
    restart: always
    environment:
        - VNC_PASSWORD=12345
    ports:
        - '5900:5900'  # VNC
        - '6900:8080'  # noVNC
    container_name: ubuntu_xfce_vnc_novnc
    image: knilix/ubuntu-xfce-vnc-novnc